export enum Categories {
  COLCHONES = 'COLCHONES',
  PLASTICOS = 'PLASTICOS',
  TUBULARES = 'TUBULARES',
  MDF = 'MDF',
  VILLAS = 'VILLAS',
  SALAS = 'SALAS',
  COCINA = 'COCINA',
  BLANCOS = 'BLANCOS',
  ELECTRODOMESTICOS = 'ELECTRODOMESTICOS',
  BASES = 'BASES',
}
